# Generated by Django 3.2.5 on 2021-08-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='address',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='cart',
            name='phoneno',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
